### ISSUE TITLE
Cloud needs to be able to close/update modals through postMessage

### ISSUE THREAD

**Issue by kmcgrady** [streamlit/streamlit-issues#29]
Chat with Emiliano about this: https://www.notion.so/S4A-Metadata-via-postMessage-089c7e4a8793443eaecb01610cd0df5a

And also this:

https://app.clubhouse.io/streamlit/story/2301/cannot-delete-app-from-sidebar-when-hamburger-menu-is-open

And then add the message type

**Comment by AnOctopus** [comment]
https://github.com/streamlit/streamlit/pull/2893 is for this
