### ISSUE TITLE
Allow Querying "was submitted" property of a form

### ISSUE THREAD

**Issue by kmcgrady** [streamlit/streamlit-issues#9]
New spec here: https://www.notion.so/streamlit/Draft-Spec-2-03bf78f24aff4071b969828713967250#73fb9e21cf5c45339d01dfe08ba4658f

```python
with st.form() as my_form:
  ...
  slider = st.slider('hello')
  ...
  # Can place this anywhere, but the form button will always appear at the end
  submitted = my_form.submit_button('Submit')

if submitted:
  st.write('Submitted')
else:
  st.write('Not yet submitted')
```

**Comment by tconkling** [comment]
Abhi and I discussed the "form button always at end" requirement. I pushed back on it as potentially unexpected (for the user) and more complex (implementation-wise), and the new plan is to just place the submit button wherever the user declares it within the form.
